// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CitySearch: typeof import('./src/citySearch.vue')['default']
    Cs: typeof import('./src/cs.vue')['default']
    CustomVcsButton: typeof import('./src/components/CustomVcsButton.vue')['default']
    TextField: typeof import('./src/components/TextField.vue')['default']
    VCard: typeof import('vuetify/lib')['VCard']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VSheet: typeof import('vuetify/lib')['VSheet']
  }
}

export { }
